# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XF_Bills' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Toaster', '~> 2.0'
	pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'
  # Pods for XF_Bills

  target 'XF_BillsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XF_BillsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


